### ISSUE TITLE
0.6.1+ Isn't working on my linux install

### ISSUE THREAD

**Issue by RedGeometryDash** [AllPoland/ArcViewer#66] opened 2024-07-10 01:08 UTC
### Describe the bug:
When loading a replay, it appears to get stuck on "loading song" and never get past that.

### How to Reproduce:

- open ArcViewer on 0.6.1 and 0.6.2.
- load a replay by pasting a Beatleader replay link or opening a .bsor file.

### Expected behavior:
Supposed to successfully load into the replay viewer.

### Build Info:
 - Platform: Linux Mint 21.3 x86_64, Kernel: 6.5.0-35-generic 
 - Version: 0.61, 0.62

### Additional context:
0.6.0 and under work fine. I'm unsure if this is exclusively happening on my distro but I assume since 0.6.0 and under work that this may be the same case for other distros.

https://github.com/AllPoland/ArcViewer/assets/63124209/d1f3cc56-6d5f-4da9-9325-05294cc78001

**Comment by AllPoland** [comment] 2024-07-12 00:37
Can you send a log after the issue occurs? Most likely something is throwing an error in loading and I can look into it.

**Comment by RedGeometryDash** [comment] 2024-07-13 00:45
after some time i was able to open the logs folder, for me at least the in game option to "Show Logs" doesnt work, it does nothing on gnome and tells me the path doesnt exist on kde "The file or folder /home/redgd/Desktop/0.6.2 (0.6.1 is the same)/~/.config/unity3d/AllPolanDev/ArcViewer/Player.log does not exist.", but i found it it in "Home/MYUSERNAME/.config/unity3d/AllPolanDev/ArcViewer/Player.log" here is all the relevant info i think.

Environment loaded.
kf.service.services: KApplicationTrader: mimeType "x-scheme-handler/file" not found
Icon theme "ubuntu-mono" not found.
Icon theme "yaru" not found.
Icon theme "elementary" not found.
Icon theme "bloom" not found.
Searching for replay from score ID: 16337531
Searching for replay from: https://cdn.replays.beatleader.xyz/16337531-297255-ExpertPlus-Standard-Firestarter.bsor
Starting download.
Successfully saved atdpt2xapj.bsor to cache.
Loaded replay for Firestarter, Standard, ExpertPlus, played by Red, with score 892737, and modifiers: 
Getting Beatleader user 297255
Downloading avatar from https://cdn.assets.beatleader.xyz/297255R22.png
Getting replay leaderboard info.
Loading map from preset URL: https://cdn.songs.beatleader.xyz/Firestarter.zip
Downloading map data from: https://cdn.songs.beatleader.xyz/Firestarter.zip
Starting download.
Successfully saved ia7f77leao.zip to cache.
Info.dat is version: 2.1.0
Parsing Info.dat in V2 format.
Loaded info for Tanger - Firestarter
Loading single lightshow for replay.
Standard, ExpertPlus has no lightshow attached.
Loading single difficulty for replay.
Loading Standard, ExpertPlus
StandardExpertPlus.dat is version: 3.0.0
Parsing StandardExpertPlus.dat in V3 format.
Parsed StandardExpertPlus.dat with 1131 notes, 14 bombs, 21 walls, 85 arcs, 7 chains.
Loading audio file.
Writing Firestarter.ogg to temp file.
Audio is mime type application/x-ogg
Loading audio file with type of OGGVORBIS.
UriFormatException: Invalid URI: The hostname could not be parsed.
  at System.Uri.CreateThis (System.String uri, System.Boolean dontEscape, System.UriKind uriKind) [0x0007b] in <a97013b7f2a14b5f80cdb58e465ddca4>:0 
  at System.Uri..ctor (System.String uriString) [0x00014] in <a97013b7f2a14b5f80cdb58e465ddca4>:0 
  at AudioFileHandler.GetAudioFromFile (System.String path, UnityEngine.AudioType type) [0x0007c] in <0ed6ecb9822b40749fdc6b5827d1a61a>:0 
  at AudioFileHandler.LoadAudioDirectory (System.String directory, System.String filename) [0x00110] in <0ed6ecb9822b40749fdc6b5827d1a61a>:0 
  at ZipReader.AudioClipFromMemoryStream (System.IO.MemoryStream stream, System.String songFilename) [0x00118] in <0ed6ecb9822b40749fdc6b5827d1a61a>:0 
  at ZipReader.GetMap () [0x002b4] in <0ed6ecb9822b40749fdc6b5827d1a61a>:0 
Rethrow as AggregateException: One or more errors occurred. (Invalid URI: The hostname could not be parsed.)
  at System.Threading.Tasks.Task.ThrowIfExceptional (System.Boolean includeTaskCanceledExceptions) [0x00011] in <a01111b1273a40cc8673b44832e8a221>:0 
  at System.Threading.Tasks.Task`1[TResult].GetResultCore (System.Boolean waitCompletionNotification) [0x0002b] in <a01111b1273a40cc8673b44832e8a221>:0 
  at System.Threading.Tasks.Task`1[TResult].get_Result () [0x0000f] in <a01111b1273a40cc8673b44832e8a221>:0 
  at MapLoader+<LoadMapFileCoroutine>d__18.MoveNext () [0x00081] in <0ed6ecb9822b40749fdc6b5827d1a61a>:0 
  at UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) [0x00026] in <799d47ea3fd1460380efad1aacedaf7c>:0 

kf.service.services: KApplicationTrader: mimeType "x-scheme-handler/file" not found
Icon theme "ubuntu-mono" not found.
Icon theme "yaru" not found.
Icon theme "elementary" not found.
Icon theme "bloom" not found.
kf.notifications: Playing audio notification failed: Destroyed

**Comment by AllPoland** [comment] 2024-07-13 05:56
Well the "show logs" button not working is another bug I'll have to look into :p

I think I know what's causing maps not to load, I'll look into it over the next couple days.

**Comment by Qualzz** [comment] 2024-07-15 20:02
I confirm 0.6.0 works on ubuntu but later release are stuck on "Loading song"

**Comment by AllPoland** [comment] 2024-07-29 00:12
Just rolled out a potential fix in 0.6.3. If the issue is still there, or if the "show logs" button still doesn't work lmk, otherwise I'll close this issue.

**Comment by RedGeometryDash** [comment] 2024-08-01 05:41
sorry for the wait, it works now thank you :)

**Closed** 2024-08-01 18:56 UTC
Labels: bug
